(function () {
  const countries = [
    { name: 'United States', slug: 'usa', flag: '🇺🇸' },
    { name: 'Canada', slug: 'canada', flag: '🇨🇦' },
    { name: 'Brazil', slug: 'brazil', flag: '🇧🇷' },
    { name: 'Mexico', slug: 'mexico', flag: '🇲🇽' },
    { name: 'United Kingdom', slug: 'uk', flag: '🇬🇧' },
    { name: 'France', slug: 'france', flag: '🇫🇷' },
    { name: 'Germany', slug: 'germany', flag: '🇩🇪' },
    { name: 'Spain', slug: 'spain', flag: '🇪🇸' },
    { name: 'Italy', slug: 'italy', flag: '🇮🇹' },
    { name: 'Nigeria', slug: 'nigeria', flag: '🇳🇬' },
    { name: 'South Africa', slug: 'south-africa', flag: '🇿🇦' },
    { name: 'Egypt', slug: 'egypt', flag: '🇪🇬' },
    { name: 'Saudi Arabia', slug: 'saudi-arabia', flag: '🇸🇦' },
    { name: 'India', slug: 'india', flag: '🇮🇳' },
    { name: 'China', slug: 'china', flag: '🇨🇳' },
    { name: 'Japan', slug: 'japan', flag: '🇯🇵' },
    { name: 'Australia', slug: 'australia', flag: '🇦🇺' },
    { name: 'New Zealand', slug: 'new-zealand', flag: '🇳🇿' },
    { name: 'Argentina', slug: 'argentina', flag: '🇦🇷' },
    { name: 'Chile', slug: 'chile', flag: '🇨🇱' },
    { name: 'Russia', slug: 'russia', flag: '🇷🇺' },
    { name: 'Sweden', slug: 'sweden', flag: '🇸🇪' },
    { name: 'Norway', slug: 'norway', flag: '🇳🇴' },
    { name: 'Finland', slug: 'finland', flag: '🇫🇮' },
    { name: 'Netherlands', slug: 'netherlands', flag: '🇳🇱' },
    { name: 'Belgium', slug: 'belgium', flag: '🇧🇪' },
    { name: 'Switzerland', slug: 'switzerland', flag: '🇨🇭' },
    { name: 'Austria', slug: 'austria', flag: '🇦🇹' },
    { name: 'Ireland', slug: 'ireland', flag: '🇮🇪' },
    { name: 'Portugal', slug: 'portugal', flag: '🇵🇹' },
    { name: 'Greece', slug: 'greece', flag: '🇬🇷' },
    { name: 'Turkey', slug: 'turkey', flag: '🇹🇷' },
    { name: 'Israel', slug: 'israel', flag: '🇮🇱' },
    { name: 'Slovakia', slug: 'slovakia', flag: '🇸🇰' },
    { name: 'Czech Republic', slug: 'czech-republic', flag: '🇨🇿' },
    { name: 'Poland', slug: 'poland', flag: '🇵🇱' },
    { name: 'Hungary', slug: 'hungary', flag: '🇭🇺' },
    { name: 'Romania', slug: 'romania', flag: '🇷🇴' },
    { name: 'Bulgaria', slug: 'bulgaria', flag: '🇧🇬' },
    { name: 'Croatia', slug: 'croatia', flag: '🇭🇷' },
    { name: 'Slovenia', slug: 'slovenia', flag: '🇸🇮' },
    { name: 'Estonia', slug: 'estonia', flag: '🇪🇪' },
    { name: 'Latvia', slug: 'latvia', flag: '🇱🇻' },
    { name: 'Lithuania', slug: 'lithuania', flag: '🇱🇹' },
    { name: 'Malta', slug: 'malta', flag: '🇲🇹' },
    { name: 'Cyprus', slug: 'cyprus', flag: '🇨🇾' },
    { name: 'Malaysia', slug: 'malaysia', flag: '🇲🇾' },
    { name: 'Philippines', slug: 'philippines', flag: '🇵🇭' },
    { name: 'Singapore', slug: 'singapore', flag: '🇸🇬' },
    { name: 'Thailand', slug: 'thailand', flag: '🇹🇭' },
    { name: 'Vietnam', slug: 'vietnam', flag: '🇻🇳' },
    { name: 'Indonesia', slug: 'indonesia', flag: '🇮🇩' },
    { name: 'Pakistan', slug: 'pakistan', flag: '🇵🇰' },
    { name: 'Bangladesh', slug: 'bangladesh', flag: '🇧🇩' },
    { name: 'Nepal', slug: 'nepal', flag: '🇳🇵' },
    { name: 'Sri Lanka', slug: 'sri-lanka', flag: '🇱🇰' },
    { name: 'Myanmar', slug: 'myanmar', flag: '🇲🇲' },
    { name: 'Cambodia', slug: 'cambodia', flag: '🇰🇭' },
    { name: 'Laos', slug: 'laos', flag: '🇱🇦' },
    { name: 'Mongolia', slug: 'mongolia', flag: '🇲🇳' },
    { name: 'Bhutan', slug: 'bhutan', flag: '🇧🇹' },
    { name: 'Nicaragua', slug: 'nicaragua', flag: '🇳🇮' },
    { name: 'Costa Rica', slug: 'costa-rica', flag: '🇨🇷' },
    { name: 'Panama', slug: 'panama', flag: '🇵🇦' },
    { name: 'Honduras', slug: 'honduras', flag: '🇭🇳' },
    { name: 'El Salvador', slug: 'el-salvador', flag: '🇸🇻' },
    { name: 'Guatemala', slug: 'guatemala', flag: '🇬🇹' },
    { name: 'Haiti', slug: 'haiti', flag: '🇭🇹' },
    { name: 'Dominican Republic', slug: 'dominican-republic', flag: '🇩🇴' },
    { name: 'Cuba', slug: 'cuba', flag: '🇨🇺' },
    { name: 'Jamaica', slug: 'jamaica', flag: '🇯🇲' },
    { name: 'Trinidad and Tobago', slug: 'trinidad-and-tobago', flag: '🇹🇹' },
    { name: 'Bahamas', slug: 'bahamas', flag: '🇧🇸' },
    { name: 'Barbados', slug: 'barbados', flag: '🇧🇧' }, 
    { name: 'Antigua and Barbuda', slug: 'antigua-and-barbuda', flag: '🇦🇬' },
    { name: 'Bahamas', slug: 'bahamas', flag: '🇧🇸' },
    { name: 'Barbados', slug: 'barbados', flag: '🇧🇧' },
    { name: 'Belize', slug: 'belize', flag: '🇧🇿' },
    { name: 'Costa Rica', slug: 'costa-rica', flag: '🇨🇷' },
    { name: 'Dominica', slug: 'dominica', flag: '🇩🇲' },
    { name: 'El Salvador', slug: 'el-salvador', flag: '🇸🇻' },
    { name: 'Grenada', slug: 'grenada', flag: '🇬🇩' },
    { name: 'Haiti', slug: 'haiti', flag: '🇭🇹' },
    { name: 'Jamaica', slug: 'jamaica', flag: '🇯🇲' },
    { name: 'St. Kitts and Nevis', slug: 'st-kitts-and-nevis', flag: '🇰🇳' },
    { name: 'St. Lucia', slug: 'st-lucia', flag: '🇱🇨' },
    { name: 'St. Vincent and the Grenadines', slug: 'st-vincent-and-the-grenadines', flag: '🇻🇨' },
    { name: 'Suriname', slug: 'suriname', flag: '🇸🇷' },
    { name: 'Trinidad and Tobago', slug: 'trinidad-and-tobago', flag: '🇹🇹' },
    { name: 'Uruguay', slug: 'uruguay', flag: '🇺🇾' },
    { name: 'Venezuela', slug: 'venezuela', flag: '🇻🇪' },
    { name: 'Virgin Islands', slug: 'virgin-islands', flag: '🇻🇮' },
  ];

  const bySlug = countries.reduce((acc, country) => {
    acc[country.slug] = country;
    return acc;
  }, {});

  const slugByName = countries.reduce((acc, country) => {
    acc[country.name] = country.slug;
    return acc;
  }, {});

  window.countryData = countries;
  window.countryBySlug = bySlug;
  window.countrySlugByName = slugByName;
})();
